### ISSUE TITLE
Runtime incompatibility with Gradle 2.x while building plugin itself with Gradle 3.x+

### ISSUE THREAD

**Issue by szpak** [mockito/shipkit#413]
Writing regression tests for Gradle versions I have noticed an incompatibility runtime incompatibility in Gradle which prevent the plugin build with Gradle 3.x+ to be executed in Gradle 2.x project.

```
org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'junit8236258207488845406'.
(...)
Caused by: java.lang.NoSuchMethodError: org.gradle.api.internal.TaskOutputsInternal.file(Ljava/lang/Object;)Lorg/gradle/api/tasks/TaskOutputFilePropertyBuilder;
	at org.shipkit.internal.gradle.notes.ReleaseNotesPlugin$2.execute(ReleaseNotesPlugin.java:82)
	at org.shipkit.internal.gradle.notes.ReleaseNotesPlugin$2.execute(ReleaseNotesPlugin.java:69)
	at org.shipkit.internal.gradle.util.TaskMaker.configure(TaskMaker.java:32)
	at org.shipkit.internal.gradle.util.TaskMaker.task(TaskMaker.java:27)
	at org.shipkit.internal.gradle.notes.ReleaseNotesPlugin.releaseNotesTasks(ReleaseNotesPlugin.java:69)
	at org.shipkit.internal.gradle.notes.ReleaseNotesPlugin.apply(ReleaseNotesPlugin.java:50)
	at org.shipkit.internal.gradle.notes.ReleaseNotesPlugin.apply(ReleaseNotesPlugin.java:39)
	at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
	at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:43)
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:137)
	at org.gradle.api.internal.plugins.DefaultPluginManager.addImperativePlugin(DefaultPluginManager.java:67)
	at org.gradle.api.internal.plugins.DefaultPluginManager.addImperativePlugin(DefaultPluginManager.java:73)
	at org.gradle.api.internal.plugins.DefaultPluginContainer.apply(DefaultPluginContainer.java:60)
	at org.shipkit.internal.gradle.release.ReleasePlugin.apply(ReleasePlugin.java:45)
	at org.shipkit.internal.gradle.release.ReleasePlugin.apply(ReleasePlugin.java:37)
	at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
	at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:43)
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:137)
	at org.gradle.api.internal.plugins.DefaultPluginManager.addImperativePlugin(DefaultPluginManager.java:67)
	at org.gradle.api.internal.plugins.DefaultPluginManager.addImperativePlugin(DefaultPluginManager.java:73)
	at org.gradle.api.internal.plugins.DefaultPluginContainer.apply(DefaultPluginContainer.java:60)
	at org.shipkit.internal.gradle.bintray.BintrayReleasePlugin.apply(BintrayReleasePlugin.java:37)
	at org.shipkit.internal.gradle.bintray.BintrayReleasePlugin.apply(BintrayReleasePlugin.java:34)
	at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
	at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:43)
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:137)
	at org.gradle.api.internal.plugins.DefaultPluginManager.addImperativePlugin(DefaultPluginManager.java:67)
	at org.gradle.api.internal.plugins.DefaultPluginManager.addImperativePlugin(DefaultPluginManager.java:73)
	at org.gradle.api.internal.plugins.DefaultPluginContainer.apply(DefaultPluginContainer.java:60)
	at org.shipkit.internal.gradle.java.ShipkitJavaPlugin.apply(ShipkitJavaPlugin.java:33)
	at org.shipkit.internal.gradle.java.ShipkitJavaPlugin.apply(ShipkitJavaPlugin.java:29)
	at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
	at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:43)
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:137)
	at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:112)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:113)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:36)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:80)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:136)
	at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:46)
	at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.java:34)
	at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
	at build_om61xg1am15hn0ymi47z8lp3.run(/tmp/junit8236258207488845406/build.gradle:15)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
	... 60 more
```

In fact the (now internal) API has been changed in Gradle 3.0 and `TaskOutput.file(...)` started to return `TaskOutputFilePropertyBuilder` instead of `TaskOutputs` itself. I don't know it we can workaround it without loosing Gradle 2 compatibility (on the other hand, is it worth to keep it?)

**Comment by szczepiq** [comment]
I think this was fixed. @szpak, reopen if needed!
