### ISSUE TITLE
CI build failed due to NPE in findOpenPullRequest

### ISSUE THREAD

**Issue by mockitoguy** [mockito/shipkit#621]
CI build failed due to NPE in findOpenPullRequest.

Full log: [Travis CI link](https://travis-ci.org/mockito/shipkit/builds/337332652)

Relevant part of the log:

```
  External process [performRelease] completed.
  Upgrading downstream projects:
    ./gradlew upgradeDownstream
[upgradeDownstream] Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
[upgradeDownstream]   Building version '1.0.9' (value loaded from 'version.properties' file).
[upgradeDownstream]   [INCUBATING] upgrade-dependency plugin is incubating and may change in any version.
[upgradeDownstream]   [INCUBATING] downstream-testing plugin is incubating and may change in any version.
[upgradeDownstream] :cloneMockitoShipkit
[upgradeDownstream]   Cloning repository https://github.com/mockito/shipkit
[upgradeDownstream]     into /home/travis/build/mockito/shipkit/build/downstream/mockitoShipkit
[upgradeDownstream]   Executing:
[upgradeDownstream]     git clone https://github.com/mockito/shipkit /home/travis/build/mockito/shipkit/build/downstream/mockitoShipkit
[upgradeDownstream] :shipkit:upgradeMockitoShipkit
[upgradeDownstream]   Upgrading dependency:
[upgradeDownstream]     ./gradlew performVersionUpgrade -Pdependency=org.shipkit:shipkit:1.0.8
[upgradeDownstream] [performVersionUpgrade] Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
[upgradeDownstream] [performVersionUpgrade]   Building version '1.0.9' (value loaded from 'version.properties' file).
[upgradeDownstream] [performVersionUpgrade]   [INCUBATING] upgrade-dependency plugin is incubating and may change in any version.
[upgradeDownstream] [performVersionUpgrade]   [INCUBATING] downstream-testing plugin is incubating and may change in any version.
[upgradeDownstream] [performVersionUpgrade] :checkoutBaseBranch
[upgradeDownstream] [performVersionUpgrade]   Executing:
[upgradeDownstream] [performVersionUpgrade]     git checkout master
[upgradeDownstream] [performVersionUpgrade] :identifyGitOrigin
[upgradeDownstream] [performVersionUpgrade]   Executing:
[upgradeDownstream] [performVersionUpgrade]     git remote get-url origin
[upgradeDownstream] [performVersionUpgrade]   Identified Git origin repository: mockito/shipkit
[upgradeDownstream] [performVersionUpgrade] :pullUpstream
[upgradeDownstream] [performVersionUpgrade]   'git pull' uses GitHub write token
[upgradeDownstream] [performVersionUpgrade]   Executing:
[upgradeDownstream] [performVersionUpgrade]     git pull https://dummy:[SECRET]@github.com/mockito/shipkit.git master
[upgradeDownstream] [performVersionUpgrade] :findOpenPullRequest
[upgradeDownstream] [performVersionUpgrade]   New pull request will be opened because we didn't find an existing PR to reuse.
[upgradeDownstream] [performVersionUpgrade] :findOpenPullRequest FAILED
[upgradeDownstream] [performVersionUpgrade] 
[upgradeDownstream] [performVersionUpgrade] FAILURE: Build failed with an exception.
[upgradeDownstream] [performVersionUpgrade] 
[upgradeDownstream] [performVersionUpgrade] * What went wrong:
[upgradeDownstream] [performVersionUpgrade] Execution failed for task ':findOpenPullRequest'.
[upgradeDownstream] [performVersionUpgrade] > java.lang.NullPointerException (no error message)
[upgradeDownstream] [performVersionUpgrade] 
[upgradeDownstream] [performVersionUpgrade] * Try:
[upgradeDownstream] [performVersionUpgrade] 
[upgradeDownstream] [performVersionUpgrade] BUILD FAILED
[upgradeDownstream] [performVersionUpgrade] 
[upgradeDownstream] [performVersionUpgrade] Total time: 7.466 secs
[upgradeDownstream] [performVersionUpgrade] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
[upgradeDownstream]   External process [performVersionUpgrade] completed.
[upgradeDownstream] :shipkit:upgradeMockitoShipkit FAILED
[upgradeDownstream] 
[upgradeDownstream] FAILURE: Build failed with an exception.
[upgradeDownstream] 
[upgradeDownstream] * What went wrong:
[upgradeDownstream] Execution failed for task ':shipkit:upgradeMockitoShipkit'.
[upgradeDownstream] > External process failed with exit code 1
[upgradeDownstream]   Please inspect the command output prefixed with '[performVersionUpgrade]' the build log.
[upgradeDownstream] 
[upgradeDownstream] * Try:
[upgradeDownstream] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
[upgradeDownstream] 
[upgradeDownstream] BUILD FAILED
[upgradeDownstream] 
[upgradeDownstream] Total time: 15.58 secs
  External process [upgradeDownstream] completed.
:ciPerformRelease FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':ciPerformRelease'.
> External process failed with exit code 1
  Please inspect the command output prefixed with '[upgradeDownstream]' the build log.
* Try:
Run with --info or --debug option to get more log output.
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':ciPerformRelease'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:153)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:150)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:99)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:48)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:239)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:212)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:205)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:55)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:36)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:31)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: org.gradle.api.GradleException: External process failed with exit code 1
Please inspect the command output prefixed with '[upgradeDownstream]' the build log.
	at org.shipkit.internal.gradle.exec.ExecCommandFactory.ensureSucceeded(ExecCommandFactory.java:61)
	at org.shipkit.internal.gradle.exec.ExecCommandFactory$4.execute(ExecCommandFactory.java:53)
	at org.shipkit.internal.gradle.exec.ExecCommandFactory$4.execute(ExecCommandFactory.java:51)
	at org.shipkit.internal.gradle.exec.ShipkitExec.execCommands(ShipkitExec.java:35)
	at org.shipkit.gradle.exec.ShipkitExecTask.execCommands(ShipkitExecTask.java:23)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:228)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:621)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:604)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 60 more
BUILD FAILED
Total time: 1 mins 0.492 secs
```

**Comment by mockitoguy** [comment]
On it.

**Comment by epeee** [comment]
this one is fixed now -> closing
