### ISSUE TITLE
deprecation warning: The baseName property has been deprecated 

### ISSUE THREAD

**Issue by epeee** [mockito/shipkit#848]
while using gradle 6.0-rc-1, see

```
The baseName property has been deprecated. This is scheduled to be removed in Gradle 7.0. Please use the archiveBaseName property instead.
        at org.gradle.api.tasks.bundling.AbstractArchiveTask.getBaseName(AbstractArchiveTask.java:220)
        at org.gradle.api.tasks.bundling.Jar_Decorated.getBaseName(Unknown Source)
        at org.shipkit.internal.gradle.java.ComparePublicationsPlugin.getBasePreviousVersionArtifactPath(ComparePublicationsPlugin.java:122)
        at org.shipkit.internal.gradle.java.ComparePublicationsPlugin.apply(ComparePublicationsPlugin.java:63)
        at org.shipkit.internal.gradle.java.ComparePublicationsPlugin.apply(ComparePublicationsPlugin.java:46)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:43)
```

for details

**Comment by mockitoguy** [comment]
Thanks for reporting! @epeee, do you want to take a stab at it?

**Comment by epeee** [comment]
@mockitoguy yep, I will have a look at it.

**Comment by Bukama** [comment]
> @mockitoguy yep, I will have a look at it. 

Hey everyone,
any progress here?
